services:
  - type: web
    name: kolkata-route-prediction
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn delhi_air_route.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
